import './global.css';
import Header from './shared/widgets/header/Header';
import { roboto } from './fonts'


export const metadata = {
  title: 'Easy ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}</body>
    </html>
  );
}
