export const shopCategories = [
  { value: "mobile", label: "Mobile Phones & Accessories" },
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "fashion_men", label: "Men's Fashion" },
  { value: "fashion_women", label: "Women's Fashion" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "home", label: "Home & Kitchen" },
  { value: "appliances", label: "Large Appliances" },
  { value: "computers", label: "Computers & Laptops" },
  { value: "gaming", label: "Gaming" },
  { value: "sports", label: "Sports & Outdoors" },
  { value: "toys", label: "Toys & Baby Products" },
  { value: "books", label: "Books & Stationery" },
  { value: "supermarket", label: "Supermarket & Groceries" },
  { value: "health", label: "Health & Wellness" },
  { value: "automotive", label: "Automotive & Motorbike" },
  { value: "furniture", label: "Furniture" },
  { value: "pet_supplies", label: "Pet Supplies" },
  { value: "jewelry", label: "Jewelry & Watches" },
];
