export const countries = [
  { code: "EG", name: "Egypt", dial_code: "+20" },
  { code: "SA", name: "Saudi Arabia", dial_code: "+966" },
  { code: "AE", name: "United Arab Emirates", dial_code: "+971" },
  { code: "US", name: "United States", dial_code: "+1" },
  { code: "GB", name: "United Kingdom", dial_code: "+44" },
  { code: "IN", name: "India", dial_code: "+91" },
  { code: "CA", name: "Canada", dial_code: "+1" },
  { code: "FR", name: "France", dial_code: "+33" },
  { code: "DE", name: "Germany", dial_code: "+49" },
  { code: "IT", name: "Italy", dial_code: "+39" },
  { code: "ES", name: "Spain", dial_code: "+34" },
  { code: "AR", name: "Argentina", dial_code: "+54" },
  { code: "MX", name: "Mexico", dial_code: "+52" },
  { code: "RU", name: "Russia", dial_code: "+7" },
  { code: "CN", name: "China", dial_code: "+86" },
  { code: "JP", name: "Japan", dial_code: "+81" },
  { code: "KR", name: "South Korea", dial_code: "+82" },
  { code: "AU", name: "Australia", dial_code: "+61" },
  { code: "NZ", name: "New Zealand", dial_code: "+64" },
  { code: "ZA", name: "South Africa", dial_code: "+27" },
  { code: "NG", name: "Nigeria", dial_code: "+234" },
  { code: "KE", name: "Kenya", dial_code: "+254" },
  { code: "GH", name: "Ghana", nameAr: "غانا", dial_code: "+233" },
  { code: "SD", name: "Sudan", dial_code: "+249" },
  { code: "QA", name: "Qatar", dial_code: "+974" },
  { code: "KW", name: "Kuwait", dial_code: "+965" },
  { code: "BH", name: "Bahrain", dial_code: "+973" },
  { code: "OM", name: "Oman", dial_code: "+968" },
  { code: "JO", name: "Jordan", dial_code: "+962" },
  { code: "LB", name: "Lebanon", dial_code: "+961" },
  { code: "IQ", name: "Iraq", dial_code: "+964" },
  { code: "TR", name: "Turkey", dial_code: "+90" },
  { code: "PK", name: "Pakistan", dial_code: "+92" },
  { code: "BD", name: "Bangladesh", dial_code: "+880" },
  { code: "PH", name: "Philippines", dial_code: "+63" },
  { code: "TH", name: "Thailand", dial_code: "+66" },
  { code: "VN", name: "Vietnam", dial_code: "+84" },
  { code: "SG", name: "Singapore", dial_code: "+65" },
  { code: "MY", name: "Malaysia", dial_code: "+60" },
  { code: "ID", name: "Indonesia", dial_code: "+62" },
  { code: "IR", name: "Iran", dial_code: "+98" },
  { code: "AF", name: "Afghanistan", dial_code: "+93" },
  { code: "ET", name: "Ethiopia", dial_code: "+251" },
  { code: "TZ", name: "Tanzania", dial_code: "+255" },
  { code: "UG", name: "Uganda", dial_code: "+256" },
  { code: "DZ", name: "Algeria", dial_code: "+213" },
  { code: "MA", name: "Morocco", dial_code: "+212" },
  { code: "TN", name: "Tunisia", dial_code: "+216" },
  { code: "LY", name: "Libya", dial_code: "+218" }
];
