import './global.css';
// import Header from "./shared/widgets/header/Header";
import { Poppins, Roboto } from 'next/font/google';
import ReactQueryProvider from './providers/provider';
import { ToasterClient } from '../shared/components/toast/ToasterClient';

export const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const poppins = Poppins({
  weight: ['300', '400', '500', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-poppins',
});

export const metadata = {
  title: 'Easy Shop',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`min-h-screen  font-sans antialiased ${poppins.variable}`}>
          <ToasterClient />
        <ReactQueryProvider>
          {/* <Header /> */}
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
