import './global.css';
// import Header from "./shared/widgets/header/Header";
import { Roboto } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import ReactQueryProvider from './providers/provider';

export const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const poppins = Roboto({
  weight: ['300', '400', '500', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-poppins',
});

export const metadata = {
  title: 'Easy Shop',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
          <Toaster position="bottom-right" reverseOrder={true} />{' '}
        <ReactQueryProvider>
          {/* <Header /> */}
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
